spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/social
info:
  app:
    name: katix
    microservice: social
    version: 1.0.0.v20200309
server:
  port: 8080
rest:
  host: localhost:${server.port}
  path: /${info.app.name}/${info.app.microservice}/api/v1
  dns: ${rest.host}
  users:
    path: ${rest.path}/users/
    domain_path: ${rest.dns}${rest.users.path}
  posts:
    path: ${rest.path}/posts/
    domain_path: ${rest.dns}${rest.posts.path}
  comments:
    path: ${rest.path}/posts/%s/comments/
    domain_path: ${rest.dns}${rest.comments.path}
logging:
  file: /var/log/social.log
  level:
    com:
    v8tix:
    katix: INFO
    org:
    springframework: INFO
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
