spring:
  main:
    banner-mode: "off"
  profiles:
    active:
      @activatedProperties@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
